# Tarefa 02

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os tutores
- Divirta-se :)

## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

dict_assuntos = {
        'matematica':df_mat
        ,'portugues':df_por
        ,'geografia':df_geo
        ,'ingles':df_ing
        ,'historia':df_his
        ,'fisica':df_fis
        ,'quimica':df_qui}
df_questoes = pd.DataFrame([24,18,8,8,8,12,12]
                           ,['matematica','portugues','geografia','ingles','historia','fisica','quimica']
                          ,columns=['n_questoes'])

#### Questão 1

In [2]:
lista_assunto =[]
lista_percentual_acertos =[]

for key in dict_assuntos:
    lista_assunto.append(key)
    lista_percentual_acertos.append(
            dict_assuntos[key].Qt_acertos.sum()
            /(df_questoes.loc[key]['n_questoes']*dict_assuntos[key].shape[0]))
    
df_perct_acertos = pd.DataFrame(lista_percentual_acertos,lista_assunto,columns=['Percentual'])
df_perct_acertos.index.name = 'Assunto'
df_perct_acertos

            Percentual
Assunto
matematica    0.493750
portugues     0.401667
geografia     0.420000
ingles        0.476250
historia      0.450000
fisica        0.443333
quimica       0.452500

#### Questão 2

In [3]:
df_acertos = pd.DataFrame()
for key in dict_assuntos:
    df_acertos = pd.concat([df_acertos,dict_assuntos[key]],axis=1)
df_acertos.columns = dict_assuntos.keys()
df_acertos['soma_acertos_aluno'] = df_acertos.sum(axis=1).round(2)
df_acertos

,matematica,portugues,geografia,ingles,historia,fisica,quimica,soma_acertos_aluno
0,6,7,7,3,1,8,3,35
1,19,10,0,0,0,11,8,48
2,14,16,0,5,7,4,4,50
3,10,7,3,4,0,0,8,32
4,7,2,2,7,0,9,3,30
...,...,...,...,...,...,...,...,...
95,6,4,7,1,4,9,3,34
96,8,1,4,6,1,4,3,27
97,23,5,0,2,4,1,5,40
98,0,10,3,1,5,10,11,40
99,11,15,0,1,6,7,2,42

#### Questão 3

In [4]:
df_acertos['percentual_aluno'] = (df_acertos['soma_acertos_aluno']/df_questoes.n_questoes.sum()).round(2)
df_acertos

,matematica,portugues,geografia,ingles,historia,fisica,quimica,soma_acertos_aluno,percentual_aluno
0,6,7,7,3,1,8,3,35,0.39
1,19,10,0,0,0,11,8,48,0.53
2,14,16,0,5,7,4,4,50,0.56
3,10,7,3,4,0,0,8,32,0.36
4,7,2,2,7,0,9,3,30,0.33
...,...,...,...,...,...,...,...,...,...
95,6,4,7,1,4,9,3,34,0.38
96,8,1,4,6,1,4,3,27,0.30
97,23,5,0,2,4,1,5,40,0.44
98,0,10,3,1,5,10,11,40,0.44
99,11,15,0,1,6,7,2,42,0.47

#### Questão 4

In [5]:
df_corte = df_acertos[df_acertos['soma_acertos_aluno']>45]
df_corte.shape[0]

31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

#### I

In [6]:
df_reprovados = df_acertos[(df_acertos['matematica']==0) | (df_acertos['fisica'] == 0) | (df_acertos['quimica'] == 0)]
df_reprovados

,matematica,portugues,geografia,ingles,historia,fisica,quimica,soma_acertos_aluno,percentual_aluno
3,10,7,3,4,0,0,8,32,0.36
6,6,0,7,7,5,0,4,29,0.32
10,10,8,3,2,1,7,0,31,0.34
12,20,8,3,7,1,0,3,42,0.47
14,7,11,1,7,1,4,0,31,0.34
20,23,11,6,5,6,2,0,53,0.59
25,0,4,7,4,0,4,8,27,0.30
26,11,14,6,2,7,0,0,40,0.44
27,21,13,1,5,7,3,0,50,0.56
33,14,8,0,5,6,6,0,39,0.43
35,11,14,6,3,3,0,11,48,0.53
49,8,1,1,0,1,0,8,19,0.21
56,7,6,7,5,6,0,8,39,0.43
65,1,8,2,4,3,0,6,24,0.27
66,5,4,3,6,3,0,10,31,0.34
72,11,16,3,4,7,0,9,50,0.56
73,1,16,2,4,3,0,11,37,0.41
74,9,11,0,7,5,7,0,39,0.43
84,15,1,0,5,1,0,4,26,0.29
89,23,11,7,7,6,9,0,63,0.70
92,14,10,1,6,1,8,0,40,0.44
94,0,5,2,6,1,3,8,25,0.28
98,0,10,3,1,5,10,11,40,0.44

#### II

In [7]:
df_reprovados.shape[0]

23

#### III

In [8]:
df_reprovados[['historia','geografia']].mean().to_frame()

                  0
historia   3.434783
geografia  3.217391

#### III

In [9]:
df_aprovados = df_acertos[~((df_acertos['matematica']==0) | (df_acertos['fisica'] == 0) | (df_acertos['quimica'] == 0))]
df_aprovados

,matematica,portugues,geografia,ingles,historia,fisica,quimica,soma_acertos_aluno,percentual_aluno
0,6,7,7,3,1,8,3,35,0.39
1,19,10,0,0,0,11,8,48,0.53
2,14,16,0,5,7,4,4,50,0.56
4,7,2,2,7,0,9,3,30,0.33
5,20,2,5,3,2,9,9,50,0.56
...,...,...,...,...,...,...,...,...,...
93,12,16,5,5,6,6,6,56,0.62
95,6,4,7,1,4,9,3,34,0.38
96,8,1,4,6,1,4,3,27,0.30
97,23,5,0,2,4,1,5,40,0.44
99,11,15,0,1,6,7,2,42,0.47

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?

In [10]:
arquivo = 'https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-05-23/uf%3DAC/part-00000-63e5bee2-3684-4286-b709-7fe85483b04e.c000.csv'
vacina = pd.read_csv(arquivo,sep=';')

In [11]:
vacina.head(5)

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
0,b19cd280-474c-4c22-a35d-8c06bc04a4e0-i0b0,2e091c9a37d3f50d1d705fc80c6448c6fc69b44da9e936...,69,1951-12-28,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,210052A,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-23,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-25T03:27:19.000Z,NaN
1,d7e13d32-32fb-4e9a-a559-b0bdd7929d2b-i0b0,dd179041b80ce919ceffa504ad2eae6f9ac3d6bbdfd531...,63,1957-06-09,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-28,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-05-02T15:41:55.000Z,NaN
2,af279a98-ba1f-47ea-8214-314a98040b0d-i0b0,6734b26bccf826130ebffa66575977bbe71477b12bcf42...,69,1951-08-14,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210135,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-16,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-16T15:54:39.000Z,NaN
3,22f523ac-3eb6-45b2-9f6e-4e9906f09b5a-i0b0,54dfc421baa6a03e54c8a57f08c50b0281d40659849fbc...,19,2001-04-28,M,5,INDIGENA,120033.0,10.0,MANCIO LIMA,...,202010028,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-02,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-22T20:21:06.000Z,NaN
4,000e911b-e3a4-4114-a735-d1f2e6e3797f-i0b0,c59571e19f368d4b0cf08cd3bcabb32e5cd8baad5340f6...,65,1955-11-21,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-29,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T19:44:28.000Z,NaN

In [12]:
vacina.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174191 entries, 0 to 174190
Data columns (total 34 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   document_id                               174191 non-null  object
 1   paciente_id                               174191 non-null  object
 2   paciente_idade                            174191 non-null  int64
 3   paciente_datanascimento                   174191 non-null  object
 4   paciente_enumsexobiologico                174191 non-null  object
 5   paciente_racacor_codigo                   174191 non-null  int64
 6   paciente_racacor_valor                    174191 non-null  object
 7   paciente_endereco_coibgemunicipio         172900 non-null  float64
 8   paciente_endereco_copais                  172902 non-null  float64
 9   paciente_endereco_nmmunicipio             172902 non-null  object
 10  paciente_endereco_nmpais                  172902 non-null  object
 11  paciente_endereco_uf                      172900 non-null  object
 12  paciente_endereco_cep                     145096 non-null  float64
 13  paciente_nacionalidade_enumnacionalidade  174021 non-null  object
 14  estabelecimento_valor                     174191 non-null  int64
 15  estabelecimento_razaosocial               174191 non-null  object
 16  estalecimento_nofantasia                  174191 non-null  object
 17  estabelecimento_municipio_codigo          174191 non-null  int64
 18  estabelecimento_municipio_nome            174191 non-null  object
 19  estabelecimento_uf                        174191 non-null  object
 20  vacina_grupoatendimento_codigo            174191 non-null  int64
 21  vacina_grupoatendimento_nome              173085 non-null  object
 22  vacina_categoria_codigo                   173085 non-null  float64
 23  vacina_categoria_nome                     172457 non-null  object
 24  vacina_lote                               174191 non-null  object
 25  vacina_fabricante_nome                    174191 non-null  object
 26  vacina_fabricante_referencia              172800 non-null  object
 27  vacina_dataaplicacao                      174191 non-null  object
 28  vacina_descricao_dose                     174191 non-null  object
 29  vacina_codigo                             174191 non-null  int64
 30  vacina_nome                               174191 non-null  object
 31  sistema_origem                            174191 non-null  object
 32  data_importacao_rnds                      174191 non-null  object
 33  id_sistema_origem                         0 non-null       float64
dtypes: float64(5), int64(6), object(23)
memory usage: 45.2+ MB

#### I

In [13]:
vacina.shape[0]

174191

#### II

In [14]:
len(vacina['paciente_id'].unique())

125009

#### III

In [34]:
primeira_dose = (vacina['vacina_descricao_dose'].unique()[0])
vacina[vacina['vacina_descricao_dose'] ==  primeira_dose]['paciente_id'].nunique()

124185

#### IV

In [58]:
len(vacina[vacina['paciente_idade'] > 18]['paciente_id'].unique())

124244

#### V

In [61]:
len(vacina['estabelecimento_valor'].unique())

103

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [66]:
# 1) 
vacina2 = vacina[vacina['paciente_idade'] <18].copy()
vacina2.head(3)

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
1659,acd193a2-9d85-4861-abfc-c155f32bf7e8-i0b0,abdd11b1cad5e0b9cde1357f0f2ef38b8b725cd6a750ef...,17,2003-09-05,M,3,PARDA,120039.0,10.0,PORTO WALTER,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-05-13,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-05-19T21:32:44.000Z,NaN
15757,fdb8d3b6-14d9-4bcc-9cfe-acd46b4a317a-i0b0,7cf3b238383a70eeb26841c01817737c9706d5b231e8c2...,17,2004-01-23,F,99,SEM INFORMACAO,120020.0,10.0,CRUZEIRO DO SUL,...,213VCD042Z,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-05-15,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-05-18T03:17:02.000Z,NaN
28570,449dcd9c-6404-42c2-9629-e6ccc6d1d186-i0b0,6471e51225993679cc17fce1c29defb42949ec38b261eb...,17,2003-09-16,M,4,AMARELA,120033.0,10.0,MANCIO LIMA,...,202010028,FUNDACAO BUTANTAN,Organization/61189445000156,2021-02-06,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-19T14:28:09.000Z,NaN

In [68]:
# 2) 
lst_colunas = vacina2.columns
lst_colunas

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem'],
      dtype='object')

In [106]:
# 3)
vacina2['vacina_categoria_nome'].value_counts()

Povos Indígenas                     33
Povos e Comunidades Tradicionais     9
Trabalhadores de Saúde               9
Comorbidades                         2
Faixa Etária                         1
Name: vacina_categoria_nome, dtype: int64

In [100]:
# 4)
lst_colunas_estabelecimentos = []
for col in lst_colunas:
    if col.find('estabelecimento')>=0:lst_colunas_estabelecimentos.append(col)
lst_colunas_estabelecimentos

['estabelecimento_valor',
 'estabelecimento_razaosocial',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf']

In [115]:
# 5)
df_estabelecimento = vacina2.loc[:,lst_colunas_estabelecimentos]
df_estabelecimento

,estabelecimento_valor,estabelecimento_razaosocial,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1659,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,120039,PORTO WALTER,AC
15757,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
28570,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120033,MANCIO LIMA,AC
29435,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
30514,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120035,MARECHAL THAUMATURGO,AC
34846,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
38026,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,120040,RIO BRANCO,AC
41025,6992811,PREFEITURA MUNICIPAL DE SENA MADUREIRA,120050,SENA MADUREIRA,AC
41169,6992811,PREFEITURA MUNICIPAL DE SENA MADUREIRA,120050,SENA MADUREIRA,AC
42189,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,120032,JORDAO,AC
46891,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,120034,MANOEL URBANO,AC
49016,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120030,FEIJO,AC
51142,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120035,MARECHAL THAUMATURGO,AC
52410,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,120032,JORDAO,AC
59025,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
61676,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120039,PORTO WALTER,AC
66400,2000040,PREFEITURA MUNICIPAL DE FEIJO,120030,FEIJO,AC
67140,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120035,MARECHAL THAUMATURGO,AC
68894,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120020,CRUZEIRO DO SUL,AC
69728,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120033,MANCIO LIMA,AC
71721,7123043,PREFEITURA MUNICIPAL DE JORDAO,120032,JORDAO,AC
77359,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120030,FEIJO,AC
81747,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120030,FEIJO,AC
82096,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,120020,CRUZEIRO DO SUL,AC
83559,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120039,PORTO WALTER,AC
85301,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,120039,PORTO WALTER,AC
88494,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120035,MARECHAL THAUMATURGO,AC
89795,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,120025,EPITACIOLANDIA,AC
100901,6697151,MINISTERIO DA SAUDE,120050,SENA MADUREIRA,AC
105718,6612385,PREFEITURA MUNICIPAL DE TARAUACA,120060,TARAUACA,AC
106499,2000040,PREFEITURA MUNICIPAL DE FEIJO,120030,FEIJO,AC
109706,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120035,MARECHAL THAUMATURGO,AC
116849,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120035,MARECHAL THAUMATURGO,AC
120160,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120033,MANCIO LIMA,AC
120961,2000040,PREFEITURA MUNICIPAL DE FEIJO,120030,FEIJO,AC
125167,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,120040,RIO BRANCO,AC
125527,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
129351,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,120039,PORTO WALTER,AC
133970,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,120039,PORTO WALTER,AC
139352,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120030,FEIJO,AC
139932,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,120039,PORTO WALTER,AC
140738,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,120039,PORTO WALTER,AC
141027,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,120039,PORTO WALTER,AC
141892,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,120032,JORDAO,AC
153253,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120030,FEIJO,AC
155647,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120035,MARECHAL THAUMATURGO,AC
156366,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,120034,MANOEL URBANO,AC
158327,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120035,MARECHAL THAUMATURGO,AC
158756,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,120032,JORDAO,AC
159830,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,120040,RIO BRANCO,AC
163788,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,120080,PORTO ACRE,AC
164990,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120035,MARECHAL THAUMATURGO,AC
166092,6612385,PREFEITURA MUNICIPAL DE TARAUACA,120060,TARAUACA,AC
166601,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,120039,PORTO WALTER,AC
167886,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120030,FEIJO,AC
169837,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,120040,RIO BRANCO,AC
171759,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,120005,ASSIS BRASIL,AC

In [119]:
# 6)
df_estabelecimento.drop_duplicates('estabelecimento_valor',inplace=True)
df_estabelecimento

,estabelecimento_valor,estabelecimento_razaosocial,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1659,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,120039,PORTO WALTER,AC
15757,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
28570,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120033,MANCIO LIMA,AC
29435,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
30514,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120035,MARECHAL THAUMATURGO,AC
38026,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,120040,RIO BRANCO,AC
41025,6992811,PREFEITURA MUNICIPAL DE SENA MADUREIRA,120050,SENA MADUREIRA,AC
42189,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,120032,JORDAO,AC
46891,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,120034,MANOEL URBANO,AC
49016,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120030,FEIJO,AC
61676,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120039,PORTO WALTER,AC
66400,2000040,PREFEITURA MUNICIPAL DE FEIJO,120030,FEIJO,AC
68894,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,120020,CRUZEIRO DO SUL,AC
71721,7123043,PREFEITURA MUNICIPAL DE JORDAO,120032,JORDAO,AC
82096,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,120020,CRUZEIRO DO SUL,AC
89795,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,120025,EPITACIOLANDIA,AC
100901,6697151,MINISTERIO DA SAUDE,120050,SENA MADUREIRA,AC
105718,6612385,PREFEITURA MUNICIPAL DE TARAUACA,120060,TARAUACA,AC
163788,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,120080,PORTO ACRE,AC